#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="Hack Nerd Font"

bar=(
    height=24
    position=top
    blur_radius=20
    color=$BAR_COLOR
    sticky=on
    topmost=window
    padding_right=10
    padding_left=10
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:12.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:11.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=24
  background.corner_radius=7
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=7
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${default[@]}"

#LEFT
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
#source "$ITEM_DIR/front_app.sh"

#RIGHT
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
#source "$ITEM_DIR/cpu.sh"

sketchybar --update
